### ISSUE TITLE
Zinit repo deleted!!!

### ISSUE THREAD

**Issue by mayone** [mayone/dotfiles#1]
## Description
- zinit repo deleted [reddit discussion](https://www.reddit.com/r/zsh/comments/qinb6j/httpsgithubcomzdharma_has_suddenly_disappeared_i/)
    - [backup of zinit](https://github.com/zdharma-continuum/zinit)
        - [zshrc for backup zinit](https://github.com/alichtman/dotfiles/blob/master/.config/zsh/.zshrc#L49-L83)

## Proposed solution
1. Use other zsh plugin manager (preferred solution)
2. Use backup of zinit (might not be maintained anymore)
3. Waiting for miracle to happen...

**Comment by luong-komorebi** [comment]
Hi there, @mayone . Could you check your local machine for possible copy of zsh-unique-id? This repo has 0 fork so it is really hard to find a copy of it and repost on  https://github.com/zdharma-continuum

**Comment by mayone** [comment]
Hi @luong-komorebi,  I have the plugin installed, not sure is this useful or not
```console
❯ ls ~/.zinit/plugins
_local---zinit                          zinit-zsh---z-a-as-monitor              zsh-users---zsh-autosuggestions
romkatv---powerlevel10k                 zinit-zsh---z-a-bin-gem-node            zsh-users---zsh-completions
zdharma---fast-syntax-highlighting      zinit-zsh---z-a-patch-dl
zdharma---zsh-unique-id                 zinit-zsh---z-a-rust

```

**Comment by luong-komorebi** [comment]
Well, basically I was in search of any local folders that was originally made by zdharma (because they deleted their codes). zsh-unique-id was pretty hard to find but we did found it anyway. 
Otherwise I would have to bother you and lend a copy of the folder from your local  machine :D However, all is good. You should also update your config files to point to zdharma-continuum

Thank you

**Comment by mayone** [comment]
Sure, thank you for the work~

**Comment by mayone** [comment]
- Use https://github.com/zdharma-continuum as alternative
